#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/e961d4a0-1d7b-4a18-a312-12c0d0353a8d/ # 
title: RetailPLC-Raml
types:
 products: !include DataTypes/product.raml
 bill: !include DataTypes/bill.raml
 product_catagory: !include DataTypes/prodcatagory.raml


/products:
  get:
    description: fetches list of products
    responses:
      200:
       body:
         application/json:
           example:
              
            !include Examples/product.raml
  post:
    description:
    responses:
        201:
          body:
            application/json:
              example:
                
  /{product_ID}:
  
    get:
    
      responses:
        200:
          body:
            application/json:
              example:
                {"ID created successfully"}
    put:
      description: 
      responses:
        200:
          body:
            application/json:
              example:
    delete:
      description: 
      responses:
        200:
          body:
            application/json:
              example:

/bills: 
 get:
   description: retrieve all bill data
   responses:
      200:
        body:
          application/json:
            
            example:
              !include Examples/bill.raml
         
            
 post:
    description: create the bill
    responses:
      200:
        body:
          application/json:
            example:
              {}
                
 /{bill_ID}:
   description: get specific bill id 
   get:
     responses:
        200:
          body:
            application/json:
              example:
   put:
     responses:
        200:
          body:
            application/json:
              example:
                {}  
   delete:
     responses:
        200:
          body:
            application/json:
              example:
                {} 

/product_catagory:
  get:
    description: fetches list of products
    responses:
      200:
       body:
         application/json:
           example:
              {"retrieve successfully"} 
  post:
    description:
    responses:
        201:
          body:
            application/json:
              example:
                
  /{product_catagoryID}:
    get:
      responses:
        200:
          body:
            application/json:
              example:
                {"ID created successfully"}
    put:
      description: 
      responses:
        200:
          body:
            application/json:
              example:
    delete:
      description: 
      responses:
        200:
          body:
            application/json:
              example:

